### ISSUE TITLE
Use bazel as build system

### ISSUE THREAD

**Issue by symbiont-stevan-andjelkovic** [symbiont-io/detsys-testkit#74]
Currently `go` code can be built and tested using `bazel`. Other `bazel` related tasks:

- [x] Use `bazel` to build and test `python` (ldfi);
- [x] Use `bazel` to build and test `clojure` (checker, scheduler);
- [x] Use `bazel` to build uberjar and later GraalVM native image;
  - [x] Fix problem with GraalVM image not finding clojure.core libraries at run-time for checker. Fixed in: https://github.com/symbiont-io/detsys-testkit/pull/161;
  - [ ] Fix build on MacOS. rules_graal don't support $location substitutions nor C dependencies, so currently the path to zlib on linux is hardcoded.
- [x] Use `bazel` to build and test Haskell code (ldfi2);
  - [x] Fix problem with MacOS  11.2.2 Big Sur not fiding C libraries: https://github.com/tweag/rules_haskell/issues/1500; 
  - [x] Fix linking issue to z3. `ldd ./bazel-bin/src/ldfi2/ldfi2` shows `libz3.so => /home/.../detsys-testkit/./bazel-bin/src/ldfi2/../../_solib_k8/_U@haskell_Uz3_S_S_Clibz3___Ulib/libz3.so` but after `nix-env -if default.nix` then `ldd $(which detsys-ldfi)` says `libz3.so => not found` (note that when ldfi2 is built with nix we don't get this problem). Fixed in #192.
- [x] Use `bazel` in combination with `nix` (`rules_nixpkgs`);
- [x] The `--version` flag doesn't work on Golang binaries built by `bazel`;
- [x] The `--version` flag doesn't work on Clojure binaries built by `bazel`. Fixed in #205;
- [x] The `--version` flag doesn't work on Haskell binaries built by `bazel`. Fixed in #198;
  * https://stackoverflow.com/questions/49879399/bazel-how-to-access-workspace-status-variables-in-skylark
  * https://stackoverflow.com/questions/50648052/how-can-i-build-custom-rules-using-the-output-of-workspace-status-command
- [ ] Figure out where to store db's migration files in the bazel build;
- [ ] Fix `Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=x86_64, paths=[]` problem for checker in the bazel build;
- [ ] Fix `panic: no such function: json_extract` problem for debugger with bazel build;
- [ ] Use bazel from within `nix-build`: https://github.com/tweag/rules_nixpkgs/issues/73 (will this not ruin the bazel caching?);
- [x] Package up all `detsys` binaries built by `bazel` using `nix-build`: https://github.com/symbiont-io/detsys-testkit/pull/151;
- [ ] Do a nix post-install check on the packaged up binaries to ensure that they are all of the same version;
- [ ] Figure out how to use `bazel` on CI;
- [ ] Figure out how to write integration tests using `detsys` with bazel;
- [ ] Make it easy to reproduce/rebuild all the components to some specific version (that was used in some test run, so that that test run could be reproduced);
- [ ] Can we package up all binaries in a .deb or brew tarball using nix? (what happens to system dependencies e.g. libz3?)
- [ ] Document how to use `bazel` for development vs `nix` for packaging.
